---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "phpldapadmin.fullname" . }}
spec:
  ports:
    - name: {{ template "phpldapadmin.name" . }}
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ template "phpldapadmin.name" . }}
