{{- if .Values.ingress.enabled -}}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: github-cache-server
  labels:
    app: github-cache-server
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range .Values.ingress.paths }}
    - host: {{ $.Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: github-cache-server
                port:
                  number: {{ $.Values.service.port }}
    {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}