---
{{- if and .Values.podDisruptionBudget.enabled (gt (.Values.replicaCount | int) 2) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: github-cache-server
  labels:
    app: github-cache-server
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: github-cache-server
{{- end }}
