apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "system-upgrade.drainerRoleName" . }}
  labels:
    {{- include "system-upgrade.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods/eviction
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - delete
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - patch
  - apiGroups:
      - apps
    resources:
      - statefulsets
      - daemonsets
      - replicasets
    verbs:
      - get
      - list