{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "system-upgrade.fullname" . }}
  labels:
    {{- include "system-upgrade.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - upgrade.cattle.io
  resources:
  - plans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - upgrade.cattle.io
  resources:
  - plans/status
  verbs:
  - get
  - patch
  - update
{{- if .Values.rbac.additionalRules }}
{{- toYaml .Values.rbac.additionalRules | nindent 0 }}
{{- end }}
{{- end }}