{{- if .Values.controller.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "system-upgrade.fullname" . }}-config
  namespace: {{ include "system-upgrade.namespace" . }}
  labels:
    {{- include "system-upgrade.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.controller.configMap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}