apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "system-upgrade.controllerRoleName" . }}
  namespace: {{ include "system-upgrade.namespace" . }}
  labels:
    {{- include "system-upgrade.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch